### ISSUE TITLE
fix(vfs): make vfs build fails due to type mismatch and missing define

### ISSUE THREAD

**Issue by corylanou** [benbjohnson/litestream#873]
## Description

The `make vfs` target fails to build on macOS (and likely other platforms) due to two issues:

### Issue 1: Missing `-DSQLITE3VFS_LOADABLE_EXT` flag

The `vfs` target doesn't pass `-DSQLITE3VFS_LOADABLE_EXT` to the C compiler, causing `src/sqlite3vfs.h` to try to include the non-existent `sqlite3-binding.h`:

```
src/sqlite3vfs.h:7:10: fatal error: 'sqlite3-binding.h' file not found
```

### Issue 2: Type mismatch in `GoLitestreamSetTime`

After fixing issue 1, the build fails with a type conflict:

```
src/litestream-vfs.c:14:14: error: conflicting types for 'GoLitestreamSetTime'
   14 | extern char* GoLitestreamSetTime(void* db, const char* timestamp);
      |              ^
cgo-gcc-export-header-prolog:58:14: note: previous declaration is here
   58 | extern char* GoLitestreamSetTime(void* dbPtr, char* timestamp);
```

The C source declares `const char* timestamp` but the CGO-generated header exports `char* timestamp`.

## Root Cause

Introduced in commit f5b166a (feat(vfs): add observability PRAGMAs and relative time parsing #856) on Dec 1, 2025.

The pre-built binaries in `dist/` are from Nov 26 (before this change), which is why they still work.

## Fix

1. Add `-DSQLITE3VFS_LOADABLE_EXT` to the gcc command in the `vfs` Makefile target
2. Change line 14 in `src/litestream-vfs.c` from:
   ```c
   extern char* GoLitestreamSetTime(void* db, const char* timestamp);
   ```
   to:
   ```c
   extern char* GoLitestreamSetTime(void* db, char* timestamp);
   ```

## Environment

- macOS 14 (Darwin 24.6.0)
- Go 1.24+
- gcc/clang from Xcode
